### ISSUE TITLE
Markup within div

### ISSUE THREAD

**Issue by peterjc** [OBF/OBF.github.io#2]
The main page uses Mediawiki markdown for links within a div (top right blue box), which works on https://github.com/OBF/OBF.github.io/blob/master/wiki/Main_Page.mediawiki (but without the div styling) yet after pandoc results in https://github.com/OBF/OBF.github.io/blob/master/wiki/Main_Page.md (with div styling, but not the markdown links).

As along as this is the only page, it should be easy enough to fix manually post-conversion.

**Comment by itssiddhantjain** [comment]
I would like to work on this issue.

**Comment by peterjc** [comment]
Closing issue, the files pointed to are not on the current master branch. They would have been from an earlier attempt at migrating from MediaWiki to markdown using https://github.com/peterjc/mediawiki_to_git_md
